{"name": "test_01", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2\n  +1\n  -2", "trace": "def test_01():\n        print('aaa')\n>       assert 1 == 2\nE       assert 1 == 2\nE         +1\nE         -2\n\ntests\\test_db.py:14: AssertionError"}, "start": 1614763441224, "stop": 1614763441224, "uuid": "b6c84d6d-0e7d-4300-bf1d-93f044c71e27", "historyId": "321529cce179a91ee7df8be538a4e316", "testCaseId": "4059177df28568b8e5a44cdcf8a0512d", "fullName": "tests.test_db#test_01", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_db"}, {"name": "host", "value": "V_YAOGXU-NB1"}, {"name": "thread", "value": "25092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_db"}]}